const catalogoMaestroGlobal = {
    // 💊 MEDICAMENTOS Y MATERIAL MÉDICO
    "Analgésicos Orales": ["Acetaminofén", "Acettaminofen", "Acido acetilsalicilico", "Advil", "Amanty", "Apiret", "Apronax", "Aspirin", "Aspirina", "Butal", "Caloxprina", "Dipirol", "Dipirona", "Dipirona sódica", "Dol Kids", "Dolac", "Dolkids", "Femmex", "Femmex Ultra", "Fiebre Kids", "Ibufen", "Ibumax", "Ibuprofeno", "Kelac", "Ketoprofeno", "Ketorolaco", "Lisalgil", "Meloxicam", "Metamizol", "Metamizol sódico", "Metanizol", "Metanizol sódico", "Mobic", "Naprosyn", "Naproxeno", "Notolac", "Novalcina", "Novalgina", "Orudis", "Panadol", "Paracetamol", "Tachipirina", "Tachipirín", "Tapsin", "Tempra", "Thrombo ASS", "Torivas", "Ácido acetilsalicílico"], 
    "Vitaminas, Minerales y Suplementos": ["Acido folico", "Benucomplex", "Calcio", "Calcionil", "Complejo B", "Fitomenadiona", "Fumarato ferroso", "Gluconato ferroso", "Hierro", "Megestrol", "Multivitamínico", "Neurobion", "Piridoxina", "Pirodixina", "Sulfato ferroso", "Tiamina", "Vitamina C", "Vitamina D3", "Vitamina K", "Vitaminas", "Zinc", "Ácido ascórbico", "Ácido fólico"], 
    "Antihipertensivos e IECA": ["Adalat", "Amlodipina", "Betahistina", "Candesartan", "Candesartán", "Capoten", "Captopril", "Cozaar", "Enalapril", "Furosemida", "Hidroclorotiazida", "Lasix", "Losartan", "Losartán", "Nefrotal", "Nifedipina", "Norvasc", "Olmesartan", "Olmesartán", "Renitec"], 
    "Antihistamínicos y Antialérgicos": ["Aerius", "Aless", "Antialérgico sin identificar", "Benadryl", "Cetirizina", "Claritin", "Clorfeniramina", "Clorfeniramina maleato", "Desloratadina", "Difenhidramina", "Dimenhidrinato", "Dofenar", "Gravol", "Letirizina", "Loratadina", "Zyrtec"], 
    "Antieméticos y Antidiarreicos": ["Aerogastrol", "Digicel", "Imodium", "Loperamida", "Medlo", "Metoclopramida", "Metohelopramida", "Ondacetron", "Ondansetron", "Ondansetrón", "Propilox", "Zofran"], 
    "Antiinflamatorios Tópicos": ["Aflamax", "Analgésico tópico", "Arnica gel", "Compresas de calor o frío", "Dencorub", "Dexquetoprofeno", "Diclofenac", "Diclofenac detilamico", "Diclofenac dietilamónico", "Diclofenac potásico", "Diclofenac sódico", "Diclofenac ácido", "Diclofenaco", "Dicloret", "Flogocox", "Muscoril", "Parche para el dolor", "Parches para el dolor", "Pomada árnica", "Tiocolchicocido", "Tiocolchicosido", "Voltaren", "Voltarén", "Árnica"], 
    "Soluciones Intravenosas": ["Agua destilada", "Cloruro de sodio 0.9%", "Dextrosa 5%", "Ringer lactato", "Solución fisiológica", "Solución Ringer", "SSN", "Suero fisiológico"], 
    "Antisépticos para Heridas": ["Agua oxigenada", "Clenosan", "Isodine", "Isopray", "Mercurocromo", "Merthiolate", "Peróxido de hidrógeno", "Solución yodada", "Yodo povidona", "Ácido hipocloroso"], 
    "Equipos de Acceso Vascular": ["Agujas", "Bajante", "Branula", "Bránula", "Bureta", "Catéter IV", "Equipo de infusión", "Equipo pericraneal", "Jeringa desechable", "Jeringas", "Llave de 3 vías", "Llave de 5 vías", "Macrogotero", "Mariposa", "Microgotero", "Obturador", "Regulador de flujo", "Scalp", "Set de transfusión", "Tapaheparina", "Venoclisis"], 
    "Desinfectantes de Superficies y Manos": ["Alcohol 70%", "Alcohol 96%", "Alcohol absoluto", "Alcohol antiséptico 70%", "Alcohol antiséptico 96%", "Alcohol en gel", "Bioscrub", "Clorhexidina", "Gel antibacterial", "Solución germicida"], 
    "Antiácidos y Gastroprotectores": ["Alflorex", "Alka Seltzer", "Colayte", "Detrolax", "Digefast", "Enterogermina", "Esomeprazol", "Festal", "Gerdex", "Losec", "Miovit", "Nexium", "Omeprazol", "Ondopra", "Pinuex", "Probióticos", "Prolardii", "Ranitidina", "Semiticona", "Simetricona", "Sucradel", "Sucralfato", "Vitaozono", "Zantac"], 
    "Material de Curación y Apósitos": ["Algodón", "Apósito", "Banditas", "Curitas", "Esparadrapo", "Gasas", "Gasas estériles", "Guata", "Hisopos", "Leucomed", "Leukomed", "Micropore", "Parche hidrocoloide", "Tensoplas", "Teragrip", "Vendas de yeso", "Vendas elásticas", "Yeso", "Yeso de poliéster"], 
    "Psiquiátricos — Control Especial": ["Alprazolam", "Amitriptilina", "Cliotiazepam", "Clonazepam", "Diazepam", "Escitalopram", "Kaditur", "Lexapro", "Paroxetina", "Paxil", "Rivotril", "Sertralina", "Socodopa", "Somnipax", "Tryptanol", "Valium", "Xanax", "Zoloft", "Zolpidem"], 
    "Broncodilatadores y Respiratorios": ["Ambroxol", "Atrovent", "Bisolvon", "Bodecort", "Brometo de ipratropio", "Bromexina", "Budecort", "Budesonida", "Dextrometophan", "Dextrometorfán", "Duovent", "Expectorante", "Ipratropio", "Pulmicort", "Salbumed", "Salbutamol", "Tilodrin", "Todex", "Ventolin"], 
    "Antibióticos Inyectables": ["Amikacina", "Bancomicina", "Briutcare", "Ceftazidima", "Ceftraxona", "Ceftriaxona", "Cetriaxona", "Fluconazol", "Garamicina", "Gentamicina", "Linezolid", "Meropenem", "Rocefín", "Triaxono", "Vancomicina", "Zidwime"], 
    "Antibióticos — Penicilinas y Cefalosporinas": ["Amoxicilina", "Amoxicilina con ácido clavulánico", "Amoxil", "Ampicilina", "Augmentin", "Cefadroxilo", "Cefalexina", "Cefixima", "Clavulin", "Clodoxin", "Dicloxacilina", "Dicloxacina", "Suprax", "Velamox"], 
    "Oncológicos": ["Arepitant", "Cisplatin", "Cisplatino", "Emend"], 
    "Antihipertensivos — Betabloqueantes": ["Atenolol", "Atorvastatina", "Biotranex", "Bisoprolol", "Cardevilol", "Carvedilol", "Ciclokan", "Clopidogrel", "Coranprol", "Lipitor", "Naftidrofurilo", "Plavix", "Samsusolina", "Sulfametoxazol", "Tenormin", "Ácido tranexámico"], 
    "Antibióticos — Quinolonas y Otros Orales": ["Azitromicina", "Cipro", "Ciprofloxacina", "Clindamicina", "Clindomicina", "Clorace", "Dalacin", "Doxiciclina", "Doxicilina", "Flagyl", "Levofloxacino", "Liprofloxalina", "Metronidazol", "Tavanic", "Zerodine", "Zitromax"], 
    "Antiparasitarios y Antimicóticos": ["Bacitracina", "Benznidazol", "Benzonidasol", "Canesten", "Clotrimazol", "Ivermectina", "Mycostatin", "Nistatina", "Sulfadiazina de plata"], 
    "Diagnóstico y Laboratorio": ["Bajalenguas", "Esfigmomanómetro", "Estetoscopio", "Glucómetro", "Gotas nasales", "Gotas oftálmicas", "Lancetas", "Oxímetro", "Tensiómetro", "Termómetro", "Tiras reactivas", "Tubos de ensayo"], 
    "Inmovilización y Soporte Físico": ["Bastones", "Camilla", "Collarín", "Collarín cervical", "Ferulas", "Férulas", "Muletas", "Muñequera"], 
    "Corticoides Sistémicos": ["Betametasona", "Bexametasona", "Calcort", "Celestone", "Decadrón", "Deflazacort", "Dexametasona", "Hidrocortisol", "Hidrocortisona inyectable", "Hidrocortizona", "Medrol", "Meticorten", "Metilprednisolona", "Prednisona"], 
    "Instrumental Quirúrgico": ["Bisturí", "Bolsa de orina", "Cepillo quirúrgico", "Hoja de bisturí", "Pinza umbilical", "Recolector de muestras", "Sonda uretral", "Sonda vesical", "Sutura", "Sutura quirúrgica"], 
    "Oxigenoterapia y Nebulización": ["Canula nasal", "Cánula nasal", "Humidificador", "Kit de nebulización", "Mascarilla de oxígeno", "Máscara de oxígeno", "Nebulizador", "Tubo endotraqueal"], 
    "Rehidratación y Electrolitos Orales": ["Citrato de magnesio", "Electrolitos", "Fisilin", "Hidrolit", "Hydralit", "Pedialyte", "Pediasure", "Sal de rehidratación", "Sales de rehidratación", "Sobre de electrolitos", "Suero oral", "Suero oral rehidratación", "Sulfato de magnesio"], 
    "Corticoides Tópicos": ["Cortaid", "Crema humectante", "Crema para hidratación", "Hidrocortisona crema", "Madecasol", "Vaselina", "Vasenilla"], 
    "Anticonvulsivantes y Neuropáticos": ["Dilantin", "Fenitoína", "Gabapentina", "Lyrica", "Neuromix", "Neurontin", "Nimodipina", "Nimotop", "Phenytropa", "Pregabalina", "Pregalabina", "Torsilax"], 
    "Antidiabéticos e Insulina": ["Glucofage", "Glucophage", "Humulin", "Insulina", "Lantus", "Metformina"], 
    "Indumentaria Médica": ["Centro de cama", "Cubrebotas", "Gorro de enfermera", "Gorro quirúrgico", "Guantes de látex", "Guantes de nitrilo", "Guantes de vinilo", "Mascarilla N95", "Mascarillas quirúrgicas", "Mono quirúrgico", "Traje quirúrgico", "Pañal hospitalario", "Tapabocas", "Tapabocas de tela"],

    // 🥫 VÍVERES Y ALIMENTOS
    "Alimentos No Perecederos": ["Arroz", "Pasta", "Harina PAN", "Harina de trigo", "Harina de maíz", "Caraotas negras", "Lentejas", "Frijoles", "Atún enlatado", "Sardinas enlatadas", "Aceite vegetal", "Sal", "Azúcar", "Café", "Avena", "Leche en polvo", "Mayonesa", "Salsa de tomate", "Margarina/Mantequilla", "Sopa en sobre"],
    "Alimentos Infantiles": ["Fórmula infantil", "Cerelac", "Compotas", "Cereal infantil", "Leche de continuación"],
    "Bebidas y Lácteos": ["Agua mineral (Botella 600ml)", "Agua mineral (Botellón)", "Jugos envasados", "Bebida achocolatada", "Leche líquida Larga Duración (UHT)"],

    // 🧻 HIGIENE Y LIMPIEZA
    "Higiene Personal": ["Jabón de baño", "Shampoo", "Crema dental", "Cepillo de dientes", "Desodorante", "Toallas sanitarias", "Papel higiénico", "Pañales para bebé", "Pañales para adulto", "Toallitas húmedas", "Afeitadoras", "Peines/Cepillos"],
    "Limpieza y Desinfección": ["Jabón en polvo", "Jabón de panela", "Cloro", "Desinfectante", "Esponjas", "Bolsas de basura", "Coleto", "Escoba", "Tobos/Baldes", "Pala de basura", "Lavaplatos líquido/crema"],

    // 👕 ROPA Y LOGÍSTICA
    "Ropa, Calzado y Textiles": ["Ropa de bebé", "Ropa de niño", "Ropa de niña", "Ropa de hombre", "Ropa de mujer", "Zapatos de niño", "Zapatos de adulto", "Sábanas", "Cobijas", "Toallas", "Ropa interior nueva"],
    "Material de Logística": ["Cajas de cartón", "Tirro/Cinta adhesiva", "Marcadores", "Bolsas plásticas transparentes", "Tijeras", "Etiquetas"]
};

// Catálogo Maestro (Final)