const catalogoMaestroGlobal = {
    // 💊 MEDICAMENTOS Y MATERIAL MÉDICO
    "Analgésicos Orales": ["Acetaminofén", "Acettaminofen", "Acido acetilsalicilico", "Advil", "Amanty", "Apiret", "Apronax", "Aspirin", "Aspirina", "Butal", "Caloxprina", "Dipirol", "Dipirona", "Dipirona sódica", "Dol Kids", "Dolac", "Dolkids", "Femmex", "Femmex Ultra", "Fiebre Kids", "Ibufen", "Ibumax", "Ibuprofeno", "Kelac", "Ketoprofeno", "Ketorolaco", "Lisalgil", "Meloxicam", "Metamizol", "Metamizol sódico", "Metanizol", "Metanizol sódico", "Mobic", "Naprosyn", "Naproxeno", "Notolac", "Novalcina", "Novalgina", "Orudis", "Panadol", "Paracetamol", "Tachipirina", "Tachipirín", "Tapsin", "Tempra", "Thrombo ASS", "Torivas", "Ácido acetilsalicílico"], 
    "Vitaminas, Minerales y Suplementos": ["Acido folico", "Benucomplex", "Calcio", "Calcionil", "Complejo B", "Fitomenadiona", "Fumarato ferroso", "Gluconato ferroso", "Hierro", "Megestrol", "Multivitamínico", "Neurobion", "Piridoxina", "Pirodixina", "Sulfato ferroso", "Tiamina", "Vitamina C", "Vitamina D3", "Vitamina K", "Vitaminas", "Zinc", "Ácido ascórbico", "Ácido fólico"], 
    "Antihipertensivos e IECA": ["Adalat", "Amlodipina", "Betahistina", "Candesartan", "Candesartán", "Capoten", "Captopril", "Cozaar", "Enalapril", "Furosemida", "Hidroclorotiazida", "Lasix", "Losartan", "Losartán", "Nefrotal", "Nifedipina", "Norvasc", "Olmesartan", "Olmesartán", "Renitec"], 
    "Antihistamínicos y Antialérgicos": ["Aerius", "Aless", "Antialérgico sin identificar", "Benadryl", "Cetirizina", "Claritin", "Clorfeniramina", "Clorfeniramina maleato", "Desloratadina", "Difenhidramina", "Dimenhidrinato", "Dofenar", "Gravol", "Letirizina", "Loratadina", "Zyrtec"], 
    "Antieméticos y Antidiarreicos": ["Aerogastrol", "Digicel", "Imodium", "Loperamida", "Medlo", "Metoclopramida", "Metohelopramida", "Ondacetron", "Ondansetron", "Ondansetrón", "Propilox", "Zofran"], 
    "Antiinflamatorios Tópicos": ["Aflamax", "Analgésico tópico", "Arnica gel", "Compresas de calor o frío", "Dencorub", "Dexquetoprofeno", "Diclofenac", "Diclofenac detilamico", "Diclofenac dietilamónico", "Diclofenac potásico", "Diclofenac sódico", "Diclofenac ácido", "Diclofenaco", "Dicloret", "Flogocox", "Muscoril", "Parche para el dolor", "Parches para el dolor", "Pomada árnica", "Tiocolchicocido", "Tiocolchicosido", "Voltaren", "Voltarén", "Árnica"], 
    "Soluciones Intravenosas": ["Agua destilada", "Cloruro de sodio 0.9%", "Dextrosa 5%", "Ringer lactato", "Solución fisiológica", "Solución Ringer", "SSN", "Suero fisiológico"], 
    "Antisépticos para Heridas": ["Agua oxigenada", "Clenosan", "Isodine", "Isopray", "Mercurocromo", "Merthiolate", "Peróxido de hidrógeno", "Solución yodada", "Yodo povidona", "Ácido hipocloroso"], 
    "Equipos de Acceso Vascular": ["Agujas", "Bajante", "Branula", "Bránula", "Bureta", "Catéter IV", "Equipo de infusión", "Equipo pericraneal", "Jeringa desechable", "Jeringas", "Llave de 3 vías", "Llave de 5 vías", "Macrogotero", "Mariposa", "Microgotero", "Obturador", "Regulador de flujo", "Scalp", "Set de transfusión", "Tapaheparina", "Venoclisis"], 
    "Desinfectantes de Superficies y Manos": ["Alcohol 70%", "Alcohol 96%", "Alcohol absoluto", "Alcohol antiséptico 70%", "Alcohol antiséptico 96%", "Alcohol en gel", "Bioscrub", "Clorhexidina", "Gel antibacterial", "Solución germicida"], 
    "Antiácidos y Gastroprotectores": ["Alflorex", "Alka Seltzer", "Colayte", "Detrolax", "Digefast", "Enterogermina", "Esomeprazol", "Festal", "Gerdex", "Losec", "Miovit", "Nexium", "Omeprazol", "Ondopra", "Pinuex", "Probióticos", "Prolardii", "Ranitidina", "Semiticona", "Simetricona", "Sucradel", "Sucralfato", "Vitaozono", "Zantac"], 
    "Material de Curación y Apósitos": ["Algodón", "Apósito", "Banditas", "Curitas", "Esparadrapo", "Gasas", "Gasas estériles", "Guata", "Hisopos", "Leucomed", "Leukomed", "Micropore", "Parche hidrocoloide", "Tensoplas", "Teragrip", "Vendas de yeso", "Vendas elásticas", "Yeso", "Yeso de poliéster"], 
    "Psiquiátricos — Control Especial": ["Alprazolam", "Amitriptilina", "Cliotiazepam", "Clonazepam", "Diazepam", "Escitalopram", "Kaditur", "Lexapro", "Paroxetina", "Paxil", "Rivotril", "Sertralina", "Socodopa", "Somnipax", "Tryptanol", "Valium", "Xanax", "Zoloft", "Zolpidem"], 
    "Broncodilatadores y Respiratorios": ["Ambroxol", "Atrovent", "Bisolvon", "Bodecort", "Brometo de ipratropio", "Bromexina", "Budecort", "Budesonida", "Dextrometophan", "Dextrometorfán", "Duovent", "Expectorante", "Ipratropio", "Pulmicort", "Salbumed", "Salbutamol", "Tilodrin", "Todex", "Ventolin"], 
    "Antibióticos Inyectables": ["Amikacina", "Bancomicina", "Briutcare", "Ceftazidima", "Ceftraxona", "Ceftriaxona", "Cetriaxona", "Fluconazol", "Garamicina", "Gentamicina", "Linezolid", "Meropenem", "Rocefín", "Triaxono", "Vancomicina", "Zidwime"], 
    "Antibióticos — Penicilinas y Cefalosporinas": ["Amoxicilina", "Amoxicilina con ácido clavulánico", "Amoxil", "Ampicilina", "Augmentin", "Cefadroxilo", "Cefalexina", "Cefixima", "Clavulin", "Clodoxin", "Dicloxacilina", "Dicloxacina", "Suprax", "Velamox"], 
    "Oncológicos": ["Arepitant", "Cisplatin", "Cisplatino", "Emend"], 
    "Antihipertensivos — Betabloqueantes": ["Atenolol", "Atorvastatina", "Biotranex", "Bisoprolol", "Cardevilol", "Carvedilol", "Ciclokan", "Clopidogrel", "Coranprol", "Lipitor", "Naftidrofurilo", "Plavix", "Samsusolina", "Sulfametoxazol", "Tenormin", "Ácido tranexámico"], 
    "Antibióticos — Quinolonas y Otros Orales": ["Azitromicina", "Cipro", "Ciprofloxacina", "Clindamicina", "Clindomicina", "Clorace", "Dalacin", "Doxiciclina", "Doxicilina", "Flagyl", "Levofloxacino", "Liprofloxalina", "Metronidazol", "Tavanic", "Zerodine", "Zitromax"], 
    "Antiparasitarios y Antimicóticos": ["Bacitracina", "Benznidazol", "Benzonidasol", "Canesten", "Clotrimazol", "Ivermectina", "Mycostatin", "Nistatina", "Sulfadiazina de plata"], 
    "Diagnóstico y Laboratorio": ["Bajalenguas", "Esfigmomanómetro", "Estetoscopio", "Glucómetro", "Gotas nasales", "Gotas oftálmicas", "Lancetas", "Oxímetro", "Tensiómetro", "Termómetro", "Tiras reactivas", "Tubos de ensayo"], 
    "Inmovilización y Soporte Físico": ["Bastones", "Camilla", "Collarín", "Collarín cervical", "Ferulas", "Férulas", "Muletas", "Muñequera"], 
    "Corticoides Sistémicos": ["Betametasona", "Bexametasona", "Calcort", "Celestone", "Decadrón", "Deflazacort", "Dexametasona", "Hidrocortisol", "Hidrocortisona inyectable", "Hidrocortizona", "Medrol", "Meticorten", "Metilprednisolona", "Prednisona"], 
    "Instrumental Quirúrgico": ["Bisturí", "Bolsa de orina", "Cepillo quirúrgico", "Hoja de bisturí", "Pinza umbilical", "Recolector de muestras", "Sonda uretral", "Sonda vesical", "Sutura", "Sutura quirúrgica"], 
    "Oxigenoterapia y Nebulización": ["Canula nasal", "Cánula nasal", "Humidificador", "Kit de nebulización", "Mascarilla de oxígeno", "Máscara de oxígeno", "Nebulizador", "Tubo endotraqueal"], 
    "Rehidratación y Electrolitos Orales": ["Citrato de magnesio", "Electrolitos", "Fisilin", "Hidrolit", "Hydralit", "Pedialyte", "Pediasure", "Sal de rehidratación", "Sales de rehidratación", "Sobre de electrolitos", "Suero oral", "Suero oral rehidratación", "Sulfato de magnesio"], 
    "Corticoides Tópicos": ["Cortaid", "Crema humectante", "Crema para hidratación", "Hidrocortisona crema", "Madecasol", "Vaselina", "Vasenilla"], 
    "Anticonvulsivantes y Neuropáticos": ["Dilantin", "Fenitoína", "Gabapentina", "Lyrica", "Neuromix", "Neurontin", "Nimodipina", "Nimotop", "Phenytropa", "Pregabalina", "Pregalabina", "Torsilax"], 
    "Antidiabéticos e Insulina": ["Glucofage", "Glucophage", "Humulin", "Insulina", "Lantus", "Metformina"], 
    "Indumentaria Médica": ["Centro de cama", "Cubrebotas", "Gorro de enfermera", "Gorro quirúrgico", "Guantes de látex", "Guantes de nitrilo", "Guantes de vinilo", "Mascarilla N95", "Mascarillas quirúrgicas", "Mono quirúrgico", "Traje quirúrgico", "Pañal hospitalario", "Tapabocas", "Tapabocas de tela"],

    // 🥫 VÍVERES Y ALIMENTOS
    "Alimentos No Perecederos": ["Arroz", "Pasta", "Harina PAN", "Harina de trigo", "Harina de maíz", "Caraotas negras", "Lentejas", "Frijoles", "Atún enlatado", "Sardinas enlatadas", "Aceite vegetal", "Sal", "Azúcar", "Café", "Avena", "Leche en polvo", "Mayonesa", "Salsa de tomate", "Margarina/Mantequilla", "Sopa en sobre"],
    "Alimentos Infantiles": ["Fórmula infantil", "Cerelac", "Compotas", "Cereal infantil", "Leche de continuación"],
    "Bebidas y Lácteos": ["Agua mineral (Botella 600ml)", "Agua mineral (Botellón)", "Jugos envasados", "Bebida achocolatada", "Leche líquida Larga Duración (UHT)"],

    // 🧻 HIGIENE Y LIMPIEZA
    "Higiene Personal": ["Jabón de baño", "Shampoo", "Crema dental", "Cepillo de dientes", "Desodorante", "Toallas sanitarias", "Papel higiénico", "Pañales para bebé", "Pañales para adulto", "Toallitas húmedas", "Afeitadoras", "Peines/Cepillos"],
    "Limpieza y Desinfección": ["Jabón en polvo", "Jabón de panela", "Cloro", "Desinfectante", "Esponjas", "Bolsas de basura", "Coleto", "Escoba", "Tobos/Baldes", "Pala de basura", "Lavaplatos líquido/crema"],

    // 👕 ROPA Y LOGÍSTICA
    "Ropa, Calzado y Textiles": ["Ropa de bebé", "Ropa de niño", "Ropa de niña", "Ropa de hombre", "Ropa de mujer", "Zapatos de niño", "Zapatos de adulto", "Sábanas", "Cobijas", "Toallas", "Ropa interior nueva"],
    "Material de Logística": ["Cajas de cartón", "Tirro/Cinta adhesiva", "Marcadores", "Bolsas plásticas transparentes", "Tijeras", "Etiquetas"]
};

// =========================================================
// DATOS DEL EXCEL (Cargados automáticamente)
// =========================================================
const inventarioExcel = [
    { fecha: "2026-06-29", producto: "Agua potable (botella 1.5L)", categoria: "Alimentos Frescos", cantidad: 698, obs: "" },
    { fecha: "2026-06-29", producto: "Agua potable (botella 355ml)", categoria: "Alimentos Frescos", cantidad: 3865, obs: "" },
    { fecha: "2026-06-29", producto: "Agua potable (botella 5L)", categoria: "Alimentos Frescos", cantidad: 90, obs: "" },
    { fecha: "2026-06-29", producto: "Agua potable (botella 600ml)", categoria: "Alimentos Frescos", cantidad: 1264, obs: "" },
    { fecha: "2026-06-29", producto: "Agua potable (botella 750ml)", categoria: "Alimentos Frescos", cantidad: 68, obs: "" },
    { fecha: "2026-06-29", producto: "Agua potable (botellón 18L)", categoria: "Alimentos Frescos", cantidad: 1, obs: "" },
    { fecha: "2026-06-29", producto: "Bebidas en polvo", categoria: "Alimentos Frescos", cantidad: 2, obs: "" },
    { fecha: "2026-06-29", producto: "Comida preparada (raciones)", categoria: "Alimentos Frescos", cantidad: 2, obs: "" },
    { fecha: "2026-06-29", producto: "Jamón / mortadela", categoria: "Alimentos Frescos", cantidad: 133, obs: "" },
    { fecha: "2026-06-29", producto: "Jugos (en caja)", categoria: "Alimentos Frescos", cantidad: 198, obs: "" },
    { fecha: "2026-06-29", producto: "Jugos naturales", categoria: "Alimentos Frescos", cantidad: 35, obs: "" },
    { fecha: "2026-06-29", producto: "Leche pasteurizada", categoria: "Alimentos Frescos", cantidad: 119, obs: "" },
    { fecha: "2026-06-29", producto: "Margarina / mantequilla", categoria: "Alimentos Frescos", cantidad: 70, obs: "" },
    { fecha: "2026-06-29", producto: "Masa de cachapa", categoria: "Alimentos Frescos", cantidad: 3, obs: "" },
    { fecha: "2026-06-29", producto: "Mayonesa", categoria: "Alimentos Frescos", cantidad: 1046, obs: "" },
    { fecha: "2026-06-29", producto: "Pan de sandwich", categoria: "Alimentos Frescos", cantidad: 102, obs: "" },
    { fecha: "2026-06-29", producto: "Refresco en lata", categoria: "Alimentos Frescos", cantidad: 24, obs: "" },
    { fecha: "2026-06-29", producto: "Refrescos (2L)", categoria: "Alimentos Frescos", cantidad: 11, obs: "" },
    { fecha: "2026-06-29", producto: "Refrescos/jugos (1.5L)", categoria: "Alimentos Frescos", cantidad: 1, obs: "" },
    { fecha: "2026-06-29", producto: "Rikesa o similares", categoria: "Alimentos Frescos", cantidad: 4, obs: "" },
    { fecha: "2026-06-29", producto: "Salsa de tomate", categoria: "Alimentos Frescos", cantidad: 1, obs: "" },
    { fecha: "2026-06-29", producto: "Verduras variadas", categoria: "Alimentos Frescos", cantidad: 2, obs: "" },
    { fecha: "2026-06-29", producto: "Aceite vegetal", categoria: "Alimentos No Perecederos", cantidad: 82, obs: "" },
    { fecha: "2026-06-29", producto: "Arroz", categoria: "Alimentos No Perecederos", cantidad: 2288, obs: "" },
    { fecha: "2026-06-29", producto: "Atún en lata", categoria: "Alimentos No Perecederos", cantidad: 1355, obs: "" },
    { fecha: "2026-06-29", producto: "Avena", categoria: "Alimentos No Perecederos", cantidad: 48, obs: "" },
    { fecha: "2026-06-29", producto: "Azúcar", categoria: "Alimentos No Perecederos", cantidad: 195, obs: "" },
    { fecha: "2026-06-29", producto: "Bebidas deportivas", categoria: "Alimentos No Perecederos", cantidad: 126, obs: "" },
    { fecha: "2026-06-29", producto: "Café molido", categoria: "Alimentos No Perecederos", cantidad: 155, obs: "" },
    { fecha: "2026-06-29", producto: "Caraotas negras", categoria: "Alimentos No Perecederos", cantidad: 24, obs: "" },
    { fecha: "2026-06-29", producto: "Carne enlatada", categoria: "Alimentos No Perecederos", cantidad: 5, obs: "" },
    { fecha: "2026-06-29", producto: "Cereal", categoria: "Alimentos No Perecederos", cantidad: 57, obs: "" },
    { fecha: "2026-06-29", producto: "Champiñones en lata", categoria: "Alimentos No Perecederos", cantidad: 2, obs: "" },
    { fecha: "2026-06-29", producto: "Chicha en polvo", categoria: "Alimentos No Perecederos", cantidad: 8, obs: "" },
    { fecha: "2026-06-29", producto: "Chucherías", categoria: "Alimentos No Perecederos", cantidad: 56, obs: "" },
    { fecha: "2026-06-29", producto: "Crema de arroz", categoria: "Alimentos No Perecederos", cantidad: 62, obs: "" },
    { fecha: "2026-06-29", producto: "Frutas en lata", categoria: "Alimentos No Perecederos", cantidad: 1, obs: "" },
    { fecha: "2026-06-29", producto: "Galletas dulces", categoria: "Alimentos No Perecederos", cantidad: 366, obs: "" },
    { fecha: "2026-06-29", producto: "Galletas saladas", categoria: "Alimentos No Perecederos", cantidad: 144, obs: "" },
    { fecha: "2026-06-29", producto: "Gelatina en polvo", categoria: "Alimentos No Perecederos", cantidad: 2, obs: "" },
    { fecha: "2026-06-29", producto: "Granos mixtos", categoria: "Alimentos No Perecederos", cantidad: 33, obs: "" },
    { fecha: "2026-06-29", producto: "Harina de arroz", categoria: "Alimentos No Perecederos", cantidad: 0, obs: "" },
    { fecha: "2026-06-29", producto: "Harina de maíz precocida", categoria: "Alimentos No Perecederos", cantidad: 2765, obs: "" },
    { fecha: "2026-06-29", producto: "Harina de trigo", categoria: "Alimentos No Perecederos", cantidad: 110, obs: "" },
    { fecha: "2026-06-29", producto: "Jamón endiablado", categoria: "Alimentos No Perecederos", cantidad: 125, obs: "" },
    { fecha: "2026-06-29", producto: "Leche en polvo", categoria: "Alimentos No Perecederos", cantidad: 100, obs: "" },
    { fecha: "2026-06-29", producto: "Lentejas", categoria: "Alimentos No Perecederos", cantidad: 4, obs: "" },
    { fecha: "2026-06-29", producto: "Maíz en lata", categoria: "Alimentos No Perecederos", cantidad: 3, obs: "" },
    { fecha: "2026-06-29", producto: "Pasta adulto", categoria: "Alimentos No Perecederos", cantidad: 567, obs: "" },
    { fecha: "2026-06-29", producto: "Sal", categoria: "Alimentos No Perecederos", cantidad: 18, obs: "" },
    { fecha: "2026-06-29", producto: "Sardinas en lata", categoria: "Alimentos No Perecederos", cantidad: 3570, obs: "" },
    { fecha: "2026-06-29", producto: "Tortillas de trigo", categoria: "Alimentos No Perecederos", cantidad: 60, obs: "" },
    { fecha: "2026-06-29", producto: "Biberón / tetero", categoria: "Cuidado Infantil", cantidad: 78, obs: "" },
    { fecha: "2026-06-29", producto: "Calentador de leche", categoria: "Cuidado Infantil", cantidad: 1, obs: "" },
    { fecha: "2026-06-29", producto: "Cereal de arroz/avena bebé", categoria: "Cuidado Infantil", cantidad: 15, obs: "" },
    { fecha: "2026-06-29", producto: "Champú bebé", categoria: "Cuidado Infantil", cantidad: 333, obs: "" },
    { fecha: "2026-06-29", producto: "Chupo / chupón", categoria: "Cuidado Infantil", cantidad: 16, obs: "" },
    { fecha: "2026-06-29", producto: "Clip para chupón", categoria: "Cuidado Infantil", cantidad: 1, obs: "" },
    { fecha: "2026-06-29", producto: "Cobija / arrullo bebé", categoria: "Cuidado Infantil", cantidad: 9, obs: "" },
    { fecha: "2026-06-29", producto: "Compotas / purés infantiles", categoria: "Cuidado Infantil", cantidad: 1483, obs: "" },
    { fecha: "2026-06-29", producto: "Crema antipañalitis", categoria: "Cuidado Infantil", cantidad: 4, obs: "" },
    { fecha: "2026-06-29", producto: "Embudo para lactancia", categoria: "Cuidado Infantil", cantidad: 1, obs: "" },
    { fecha: "2026-06-29", producto: "Fórmula para bebé", categoria: "Cuidado Infantil", cantidad: 52, obs: "" },
    { fecha: "2026-06-29", producto: "Galletas para bebé", categoria: "Cuidado Infantil", cantidad: 1, obs: "" },
    { fecha: "2026-06-29", producto: "Jabón de baño bebé", categoria: "Cuidado Infantil", cantidad: 331, obs: "" },
    { fecha: "2026-06-29", producto: "Juguetes estimulación", categoria: "Cuidado Infantil", cantidad: 35, obs: "" },
    { fecha: "2026-06-29", producto: "Leche de fórmula infantil", categoria: "Cuidado Infantil", cantidad: 48, obs: "" },
    { fecha: "2026-06-29", producto: "Pasta para bebé", categoria: "Cuidado Infantil", cantidad: 13, obs: "" },
    { fecha: "2026-06-29", producto: "Pañales talla 1", categoria: "Cuidado Infantil", cantidad: 399, obs: "" },
    { fecha: "2026-06-29", producto: "Pañales talla 2", categoria: "Cuidado Infantil", cantidad: 803, obs: "" },
    { fecha: "2026-06-29", producto: "Pañales talla 3", categoria: "Cuidado Infantil", cantidad: 1179, obs: "" },
    { fecha: "2026-06-29", producto: "Pañales talla 4", categoria: "Cuidado Infantil", cantidad: 2180, obs: "" },
    { fecha: "2026-06-29", producto: "Pañales talla 5", categoria: "Cuidado Infantil", cantidad: 1558, obs: "" },
    { fecha: "2026-06-29", producto: "Suero oral pediátrico", categoria: "Cuidado Infantil", cantidad: 21, obs: "" },
    { fecha: "2026-06-29", producto: "Talco para bebé", categoria: "Cuidado Infantil", cantidad: 11, obs: "" },
    { fecha: "2026-06-29", producto: "Toallitas húmedas", categoria: "Cuidado Infantil", cantidad: 3205, obs: "" },
    { fecha: "2026-06-29", producto: "Acondicionador", categoria: "Higiene Personal", cantidad: 10, obs: "" },
    { fecha: "2026-06-29", producto: "Afeitadora desechable", categoria: "Higiene Personal", cantidad: 26, obs: "" },
    { fecha: "2026-06-29", producto: "Alcohol en gel", categoria: "Higiene Personal", cantidad: 3, obs: "" },
    { fecha: "2026-06-29", producto: "Bolsas para basura", categoria: "Higiene Personal", cantidad: 177, obs: "" },
    { fecha: "2026-06-29", producto: "Cepillo dental", categoria: "Higiene Personal", cantidad: 309, obs: "" },
    { fecha: "2026-06-29", producto: "Champú", categoria: "Higiene Personal", cantidad: 60, obs: "" },
    { fecha: "2026-06-29", producto: "Cloro para agua", categoria: "Higiene Personal", cantidad: 1, obs: "" },
    { fecha: "2026-06-29", producto: "Crema para peinar", categoria: "Higiene Personal", cantidad: 9, obs: "" },
    { fecha: "2026-06-29", producto: "Desodorante", categoria: "Higiene Personal", cantidad: 226, obs: "" },
    { fecha: "2026-06-29", producto: "Detergente en polvo", categoria: "Higiene Personal", cantidad: 4, obs: "" },
    { fecha: "2026-06-29", producto: "Jabón antibacterial", categoria: "Higiene Personal", cantidad: 7, obs: "" },
    { fecha: "2026-06-29", producto: "Jabón de baño", categoria: "Higiene Personal", cantidad: 916, obs: "" },
    { fecha: "2026-06-29", producto: "Jabón de lavar ropa", categoria: "Higiene Personal", cantidad: 36, obs: "" },
    { fecha: "2026-06-29", producto: "Kit limpieza personal", categoria: "Higiene Personal", cantidad: 2, obs: "" },
    { fecha: "2026-06-29", producto: "Limpiapisos", categoria: "Higiene Personal", cantidad: 14, obs: "" },
    { fecha: "2026-06-29", producto: "Papel higiénico", categoria: "Higiene Personal", cantidad: 1917, obs: "" },
    { fecha: "2026-06-29", producto: "Pasta dental", categoria: "Higiene Personal", cantidad: 505, obs: "" },
    { fecha: "2026-06-29", producto: "Pañales para adulto", categoria: "Higiene Personal", cantidad: 420, obs: "" },
    { fecha: "2026-06-29", producto: "Tampones", categoria: "Higiene Personal", cantidad: 3, obs: "" },
    { fecha: "2026-06-29", producto: "Toallas para baño", categoria: "Higiene Personal", cantidad: 2, obs: "" },
    { fecha: "2026-06-29", producto: "Toallas sanitarias", categoria: "Higiene Personal", cantidad: 5716, obs: "" },
    { fecha: "2026-06-29", producto: "Vaselina", categoria: "Higiene Personal", cantidad: 3, obs: "" },
    { fecha: "2026-06-29", producto: "Agujas hipodérmicas", categoria: "Medicina e Insumos Médicos", cantidad: 36, obs: "" },
    { fecha: "2026-06-29", producto: "Agujas pediátricas", categoria: "Medicina e Insumos Médicos", cantidad: 454, obs: "" },
    { fecha: "2026-06-29", producto: "Analgésicos Orales", categoria: "Medicina e Insumos Médicos", cantidad: 4222, obs: "" },
    { fecha: "2026-06-29", producto: "Antibióticos Inyectables", categoria: "Medicina e Insumos Médicos", cantidad: 16, obs: "" },
    { fecha: "2026-06-29", producto: "Antibióticos Penicilinas", categoria: "Medicina e Insumos Médicos", cantidad: 322, obs: "" },
    { fecha: "2026-06-29", producto: "Antibióticos Quinolonas", categoria: "Medicina e Insumos Médicos", cantidad: 318, obs: "" },
    { fecha: "2026-06-29", producto: "Anticonvulsivantes", categoria: "Medicina e Insumos Médicos", cantidad: 57, obs: "" },
    { fecha: "2026-06-29", producto: "Antidiabéticos e Insulina", categoria: "Medicina e Insumos Médicos", cantidad: 301, obs: "" },
    { fecha: "2026-06-29", producto: "Antieméticos", categoria: "Medicina e Insumos Médicos", cantidad: 107, obs: "" },
    { fecha: "2026-06-29", producto: "Antihipertensivos", categoria: "Medicina e Insumos Médicos", cantidad: 5, obs: "" },
    { fecha: "2026-06-29", producto: "Antihipertensivos IECA", categoria: "Medicina e Insumos Médicos", cantidad: 921, obs: "" },
    { fecha: "2026-06-29", producto: "Antihistamínicos", categoria: "Medicina e Insumos Médicos", cantidad: 524, obs: "" },
    { fecha: "2026-06-29", producto: "Antiinflamatorios Tópicos", categoria: "Medicina e Insumos Médicos", cantidad: 3233, obs: "" },
    { fecha: "2026-06-29", producto: "Antiparasitarios", categoria: "Medicina e Insumos Médicos", cantidad: 56, obs: "" },
    { fecha: "2026-06-29", producto: "Antisépticos", categoria: "Medicina e Insumos Médicos", cantidad: 155, obs: "" },
    { fecha: "2026-06-29", producto: "Antiácidos", categoria: "Medicina e Insumos Médicos", cantidad: 143, obs: "" },
    { fecha: "2026-06-29", producto: "Broncodilatadores", categoria: "Medicina e Insumos Médicos", cantidad: 35, obs: "" },
    { fecha: "2026-06-29", producto: "Catéter IV", categoria: "Medicina e Insumos Médicos", cantidad: 844, obs: "" },
    { fecha: "2026-06-29", producto: "Centro de cama", categoria: "Medicina e Insumos Médicos", cantidad: 133, obs: "" },
    { fecha: "2026-06-29", producto: "Corticoides Sistémicos", categoria: "Medicina e Insumos Médicos", cantidad: 92, obs: "" },
    { fecha: "2026-06-29", producto: "Corticoides Tópicos", categoria: "Medicina e Insumos Médicos", cantidad: 11, obs: "" },
    { fecha: "2026-06-29", producto: "Desinfectantes", categoria: "Medicina e Insumos Médicos", cantidad: 516, obs: "" },
    { fecha: "2026-06-29", producto: "Diagnóstico y Lab", categoria: "Medicina e Insumos Médicos", cantidad: 432, obs: "" },
    { fecha: "2026-06-29", producto: "Equipo pericraneal", categoria: "Medicina e Insumos Médicos", cantidad: 1104, obs: "" },
    { fecha: "2026-06-29", producto: "Guantes de látex", categoria: "Medicina e Insumos Médicos", cantidad: 3830, obs: "" },
    { fecha: "2026-06-29", producto: "Guantes de nitrilo", categoria: "Medicina e Insumos Médicos", cantidad: 18829, obs: "" },
    { fecha: "2026-06-29", producto: "Guantes de vinilo", categoria: "Medicina e Insumos Médicos", cantidad: 215, obs: "" },
    { fecha: "2026-06-29", producto: "Inmovilización", categoria: "Medicina e Insumos Médicos", cantidad: 18, obs: "" },
    { fecha: "2026-06-29", producto: "Instrumental Quirúrgico", categoria: "Medicina e Insumos Médicos", cantidad: 562, obs: "" },
    { fecha: "2026-06-29", producto: "Jeringas desechables", categoria: "Medicina e Insumos Médicos", cantidad: 6528, obs: "" },
    { fecha: "2026-06-29", producto: "Llave de 3 vías", categoria: "Medicina e Insumos Médicos", cantidad: 32, obs: "" },
    { fecha: "2026-06-29", producto: "Llave de 5 vías", categoria: "Medicina e Insumos Médicos", cantidad: 3, obs: "" },
    { fecha: "2026-06-29", producto: "Macrogoteros", categoria: "Medicina e Insumos Médicos", cantidad: 385, obs: "" },
    { fecha: "2026-06-29", producto: "Mascarillas N95", categoria: "Medicina e Insumos Médicos", cantidad: 598, obs: "" },
    { fecha: "2026-06-29", producto: "Mascarillas quirúrgicas", categoria: "Medicina e Insumos Médicos", cantidad: 6921, obs: "" },
    { fecha: "2026-06-29", producto: "Material de Curación", categoria: "Medicina e Insumos Médicos", cantidad: 4616, obs: "" },
    { fecha: "2026-06-29", producto: "Microgoteros", categoria: "Medicina e Insumos Médicos", cantidad: 103, obs: "" },
    { fecha: "2026-06-29", producto: "Monos quirúrgicos", categoria: "Medicina e Insumos Médicos", cantidad: 73, obs: "" },
    { fecha: "2026-06-29", producto: "Obturador", categoria: "Medicina e Insumos Médicos", cantidad: 218, obs: "" },
    { fecha: "2026-06-29", producto: "Oncológicos", categoria: "Medicina e Insumos Médicos", cantidad: 2, obs: "" },
    { fecha: "2026-06-29", producto: "Oxigenoterapia", categoria: "Medicina e Insumos Médicos", cantidad: 62, obs: "" },
    { fecha: "2026-06-29", producto: "Pañales hospitalarios", categoria: "Medicina e Insumos Médicos", cantidad: 123, obs: "" },
    { fecha: "2026-06-29", producto: "Psiquiátricos", categoria: "Medicina e Insumos Médicos", cantidad: 1, obs: "" },
    { fecha: "2026-06-29", producto: "Rehidratación", categoria: "Medicina e Insumos Médicos", cantidad: 152, obs: "" },
    { fecha: "2026-06-29", producto: "Set de transfusión", categoria: "Medicina e Insumos Médicos", cantidad: 44, obs: "" },
    { fecha: "2026-06-29", producto: "Soluciones Intravenosas", categoria: "Medicina e Insumos Médicos", cantidad: 880, obs: "" },
    { fecha: "2026-06-29", producto: "Tapabocas tela", categoria: "Medicina e Insumos Médicos", cantidad: 826, obs: "" },
    { fecha: "2026-06-29", producto: "Tapaheparina", categoria: "Medicina e Insumos Médicos", cantidad: 47, obs: "" },
    { fecha: "2026-06-29", producto: "Vitaminas", categoria: "Medicina e Insumos Médicos", cantidad: 749, obs: "" },
    { fecha: "2026-06-29", producto: "Arnés de seguridad", categoria: "Materiales de Extracción", cantidad: 1, obs: "" },
    { fecha: "2026-06-29", producto: "Barreta de acero", categoria: "Materiales de Extracción", cantidad: 2, obs: "" },
    { fecha: "2026-06-29", producto: "Botas de seguridad (par)", categoria: "Materiales de Extracción", cantidad: 43, obs: "" },
    { fecha: "2026-06-29", producto: "Casco de seguridad", categoria: "Materiales de Extracción", cantidad: 106, obs: "" },
    { fecha: "2026-06-29", producto: "Cinta de seguridad", categoria: "Materiales de Extracción", cantidad: 1, obs: "" },
    { fecha: "2026-06-29", producto: "Cuerda de manila (metro)", categoria: "Materiales de Extracción", cantidad: 8, obs: "" },
    { fecha: "2026-06-29", producto: "Cuerda de seguridad (metro)", categoria: "Materiales de Extracción", cantidad: 8, obs: "" },
    { fecha: "2026-06-29", producto: "Discos de esmeril", categoria: "Materiales de Extracción", cantidad: 145, obs: "" },
    { fecha: "2026-06-29", producto: "Esmeril angular", categoria: "Materiales de Extracción", cantidad: 3, obs: "" },
    { fecha: "2026-06-29", producto: "Gafas de protección", categoria: "Materiales de Extracción", cantidad: 14, obs: "" },
    { fecha: "2026-06-29", producto: "Guantes de protección (par)", categoria: "Materiales de Extracción", cantidad: 1252, obs: "" },
    { fecha: "2026-06-29", producto: "Lentes de seguridad", categoria: "Materiales de Extracción", cantidad: 101, obs: "" },
    { fecha: "2026-06-29", producto: "Linterna de mano", categoria: "Materiales de Extracción", cantidad: 84, obs: "" },
    { fecha: "2026-06-29", producto: "Linterna frontal", categoria: "Materiales de Extracción", cantidad: 20, obs: "" },
    { fecha: "2026-06-29", producto: "Martillo", categoria: "Materiales de Extracción", cantidad: 30, obs: "" },
    { fecha: "2026-06-29", producto: "Mascarilla anti-polvo / respirador", categoria: "Materiales de Extracción", cantidad: 1006, obs: "" },
    { fecha: "2026-06-29", producto: "Mazo / combo", categoria: "Materiales de Extracción", cantidad: 22, obs: "" },
    { fecha: "2026-06-29", producto: "Pala", categoria: "Materiales de Extracción", cantidad: 135, obs: "" },
    { fecha: "2026-06-29", producto: "Palanca / barra de rescate", categoria: "Materiales de Extracción", cantidad: 6, obs: "" },
    { fecha: "2026-06-29", producto: "Pico / picota", categoria: "Materiales de Extracción", cantidad: 28, obs: "" },
    { fecha: "2026-06-29", producto: "Pilas AA (par)", categoria: "Materiales de Extracción", cantidad: 37, obs: "" },
    { fecha: "2026-06-29", producto: "Pilas AAA (par)", categoria: "Materiales de Extracción", cantidad: 76, obs: "" },
    { fecha: "2026-06-29", producto: "Pilas por voltaje", categoria: "Materiales de Extracción", cantidad: 11, obs: "" },
    { fecha: "2026-06-29", producto: "Sacos de propileno", categoria: "Materiales de Extracción", cantidad: 51, obs: "" },
    { fecha: "2026-06-29", producto: "Sierra manual", categoria: "Materiales de Extracción", cantidad: 7, obs: "" },
    { fecha: "2026-06-29", producto: "Tobos", categoria: "Materiales de Extracción", cantidad: 42, obs: "" },
    { fecha: "2026-06-29", producto: "Comida húmeda para gatos", categoria: "Mascotas", cantidad: 2, obs: "" },
    { fecha: "2026-06-29", producto: "Gatarina (alimento seco para gatos)", categoria: "Mascotas", cantidad: 17, obs: "" },
    { fecha: "2026-06-29", producto: "Perrarina (alimento seco para perros)", categoria: "Mascotas", cantidad: 34, obs: "" },
    { fecha: "2026-06-29", producto: "Almohada", categoria: "Otros", cantidad: 8, obs: "" },
    { fecha: "2026-06-29", producto: "Cloro (uso doméstico)", categoria: "Otros", cantidad: 7, obs: "" },
    { fecha: "2026-06-29", producto: "Cobija / frazada", categoria: "Otros", cantidad: 2, obs: "" },
    { fecha: "2026-06-29", producto: "Colchoneta de dormir", categoria: "Otros", cantidad: 74, obs: "" },
    { fecha: "2026-06-29", producto: "Colchón individual", categoria: "Otros", cantidad: 6, obs: "" },
    { fecha: "2026-06-29", producto: "Cubiertos (juego)", categoria: "Otros", cantidad: 105, obs: "" },
    { fecha: "2026-06-29", producto: "Envases plásticos", categoria: "Otros", cantidad: 91, obs: "" },
    { fecha: "2026-06-29", producto: "Guantes de limpieza", categoria: "Otros", cantidad: 3, obs: "" },
    { fecha: "2026-06-29", producto: "Kits sillas y mesas", categoria: "Otros", cantidad: 58, obs: "" },
    { fecha: "2026-06-29", producto: "Lámpara recargable", categoria: "Otros", cantidad: 9, obs: "" },
    { fecha: "2026-06-29", producto: "Papeleras", categoria: "Otros", cantidad: 4, obs: "" },
    { fecha: "2026-06-29", producto: "Platos (juego)", categoria: "Otros", cantidad: 315, obs: "" },
    { fecha: "2026-06-29", producto: "Termo / cantimplora", categoria: "Otros", cantidad: 2, obs: "" },
    { fecha: "2026-06-29", producto: "Vasos (juego)", categoria: "Otros", cantidad: 1003, obs: "" },
    { fecha: "2026-06-29", producto: "Velas", categoria: "Otros", cantidad: 146, obs: "" }
];

// =========================================================
// INICIALIZACIÓN FORZADA (Solo se ejecuta 1 vez)
// =========================================================
if (localStorage.getItem('versionExcel') !== 'Carga_Final_1') {
    // 1. Cargamos el catálogo
    localStorage.setItem('catalogoAcopio', JSON.stringify(catalogoMaestroGlobal));
    
    // 2. Metemos los datos del Excel A LA FUERZA
    localStorage.setItem('inventarioAcopio', JSON.stringify(inventarioExcel));
    
    // 3. Le decimos al navegador que ya lo hizo para que no lo borre mañana
    localStorage.setItem('versionExcel', 'Carga_Final_1');
    
    alert("¡Excel cargado con éxito! Ya puedes ver el inventario.");
}