function cargarDatosExcel() {
    const inventarioData = [
        { producto: "Agua potable (botella 1.5L)", categoria: "Alimentos Frescos", cantidad: 698 },
        { producto: "Agua potable (botella 355ml)", categoria: "Alimentos Frescos", cantidad: 3865 },
        { producto: "Agua potable (botella 5L)", categoria: "Alimentos Frescos", cantidad: 90 },
        { producto: "Agua potable (botella 600ml)", categoria: "Alimentos Frescos", cantidad: 1264 },
        { producto: "Agua potable (botella 750ml)", categoria: "Alimentos Frescos", cantidad: 68 },
        { producto: "Agua potable (botellón 18L)", categoria: "Alimentos Frescos", cantidad: 1 },
        { producto: "Bebidas en polvo", categoria: "Alimentos Frescos", cantidad: 2 },
        { producto: "Comida preparada (raciones)", categoria: "Alimentos Frescos", cantidad: 2 },
        { producto: "Jamón / mortadela", categoria: "Alimentos Frescos", cantidad: 133 },
        { producto: "Jugos (en caja)", categoria: "Alimentos Frescos", cantidad: 198 },
        { producto: "Jugos naturales", categoria: "Alimentos Frescos", cantidad: 35 },
        { producto: "Leche pasteurizada", categoria: "Alimentos Frescos", cantidad: 119 },
        { producto: "Margarina / mantequilla", categoria: "Alimentos Frescos", cantidad: 70 },
        { producto: "Masa de cachapa", categoria: "Alimentos Frescos", cantidad: 3 },
        { producto: "Mayonesa", categoria: "Alimentos Frescos", cantidad: 1046 },
        { producto: "Pan de sandwich", categoria: "Alimentos Frescos", cantidad: 102 },
        { producto: "Refresco en lata", categoria: "Alimentos Frescos", cantidad: 24 },
        { producto: "Refrescos (2L)", categoria: "Alimentos Frescos", cantidad: 11 },
        { producto: "Refrescos/jugos (1.5L)", categoria: "Alimentos Frescos", cantidad: 1 },
        { producto: "Rikesa o similares", categoria: "Alimentos Frescos", cantidad: 4 },
        { producto: "Salsa de tomate", categoria: "Alimentos Frescos", cantidad: 1 },
        { producto: "Verduras variadas", categoria: "Alimentos Frescos", cantidad: 2 },
        { producto: "Aceite vegetal", categoria: "Alimentos No Perecederos", cantidad: 82 },
        { producto: "Arroz", categoria: "Alimentos No Perecederos", cantidad: 2288 },
        { producto: "Atún en lata", categoria: "Alimentos No Perecederos", cantidad: 1355 },
        { producto: "Avena", categoria: "Alimentos No Perecederos", cantidad: 48 },
        { producto: "Azúcar", categoria: "Alimentos No Perecederos", cantidad: 195 },
        { producto: "Bebidas deportivas", categoria: "Alimentos No Perecederos", cantidad: 126 },
        { producto: "Café molido", categoria: "Alimentos No Perecederos", cantidad: 155 },
        { producto: "Caraotas negras", categoria: "Alimentos No Perecederos", cantidad: 24 },
        { producto: "Carne enlatada", categoria: "Alimentos No Perecederos", cantidad: 5 },
        { producto: "Cereal", categoria: "Alimentos No Perecederos", cantidad: 57 },
        { producto: "Champiñones en lata", categoria: "Alimentos No Perecederos", cantidad: 2 },
        { producto: "Chicha en polvo", categoria: "Alimentos No Perecederos", cantidad: 8 },
        { producto: "Chucherías", categoria: "Alimentos No Perecederos", cantidad: 56 },
        { producto: "Crema de arroz", categoria: "Alimentos No Perecederos", cantidad: 62 },
        { producto: "Frutas en lata", categoria: "Alimentos No Perecederos", cantidad: 1 },
        { producto: "Galletas dulces", categoria: "Alimentos No Perecederos", cantidad: 366 },
        { producto: "Galletas saladas", categoria: "Alimentos No Perecederos", cantidad: 144 },
        { producto: "Gelatina en polvo", categoria: "Alimentos No Perecederos", cantidad: 2 },
        { producto: "Granos mixtos", categoria: "Alimentos No Perecederos", cantidad: 33 },
        { producto: "Harina de arroz", categoria: "Alimentos No Perecederos", cantidad: 0 },
        { producto: "Harina de maíz precocida", categoria: "Alimentos No Perecederos", cantidad: 2765 },
        { producto: "Harina de trigo", categoria: "Alimentos No Perecederos", cantidad: 110 },
        { producto: "Jamón endiablado", categoria: "Alimentos No Perecederos", cantidad: 125 },
        { producto: "Leche en polvo", categoria: "Alimentos No Perecederos", cantidad: 100 },
        { producto: "Lentejas", categoria: "Alimentos No Perecederos", cantidad: 4 },
        { producto: "Maíz en lata", categoria: "Alimentos No Perecederos", cantidad: 3 },
        { producto: "Pasta adulto", categoria: "Alimentos No Perecederos", cantidad: 567 },
        { producto: "Sal", categoria: "Alimentos No Perecederos", cantidad: 18 },
        { producto: "Sardinas en lata", categoria: "Alimentos No Perecederos", cantidad: 3570 },
        { producto: "Tortillas de trigo", categoria: "Alimentos No Perecederos", cantidad: 60 },
        { producto: "Biberón / tetero", categoria: "Cuidado Infantil", cantidad: 78 },
        { producto: "Calentador de leche", categoria: "Cuidado Infantil", cantidad: 1 },
        { producto: "Cereal de arroz/avena bebé", categoria: "Cuidado Infantil", cantidad: 15 },
        { producto: "Champú bebé", categoria: "Cuidado Infantil", cantidad: 333 },
        { producto: "Chupo / chupón", categoria: "Cuidado Infantil", cantidad: 16 },
        { producto: "Clip para chupón", categoria: "Cuidado Infantil", cantidad: 1 },
        { producto: "Cobija / arrullo bebé", categoria: "Cuidado Infantil", cantidad: 9 },
        { producto: "Compotas / purés infantiles", categoria: "Cuidado Infantil", cantidad: 1483 },
        { producto: "Crema antipañalitis", categoria: "Cuidado Infantil", cantidad: 4 },
        { producto: "Embudo para lactancia", categoria: "Cuidado Infantil", cantidad: 1 },
        { producto: "Fórmula para bebé", categoria: "Cuidado Infantil", cantidad: 52 },
        { producto: "Galletas para bebé", categoria: "Cuidado Infantil", cantidad: 1 },
        { producto: "Jabón de baño bebé", categoria: "Cuidado Infantil", cantidad: 331 },
        { producto: "Juguetes estimulación", categoria: "Cuidado Infantil", cantidad: 35 },
        { producto: "Leche de fórmula infantil", categoria: "Cuidado Infantil", cantidad: 48 },
        { producto: "Pasta para bebé", categoria: "Cuidado Infantil", cantidad: 13 },
        { producto: "Pañales talla 1", categoria: "Cuidado Infantil", cantidad: 399 },
        { producto: "Pañales talla 2", categoria: "Cuidado Infantil", cantidad: 803 },
        { producto: "Pañales talla 3", categoria: "Cuidado Infantil", cantidad: 1179 },
        { producto: "Pañales talla 4", categoria: "Cuidado Infantil", cantidad: 2180 },
        { producto: "Pañales talla 5", categoria: "Cuidado Infantil", cantidad: 1558 },
        { producto: "Suero oral pediátrico", categoria: "Cuidado Infantil", cantidad: 21 },
        { producto: "Talco para bebé", categoria: "Cuidado Infantil", cantidad: 11 },
        { producto: "Toallitas húmedas", categoria: "Cuidado Infantil", cantidad: 3205 },
        { producto: "Acondicionador", categoria: "Higiene Personal", cantidad: 10 },
        { producto: "Afeitadora desechable", categoria: "Higiene Personal", cantidad: 26 },
        { producto: "Alcohol en gel", categoria: "Higiene Personal", cantidad: 3 },
        { producto: "Bolsas para basura", categoria: "Higiene Personal", cantidad: 177 },
        { producto: "Cepillo dental", categoria: "Higiene Personal", cantidad: 309 },
        { producto: "Champú", categoria: "Higiene Personal", cantidad: 60 },
        { producto: "Cloro para agua", categoria: "Higiene Personal", cantidad: 1 },
        { producto: "Crema para peinar", categoria: "Higiene Personal", cantidad: 9 },
        { producto: "Desodorante", categoria: "Higiene Personal", cantidad: 226 },
        { producto: "Detergente en polvo", categoria: "Higiene Personal", cantidad: 4 },
        { producto: "Jabón antibacterial", categoria: "Higiene Personal", cantidad: 7 },
        { producto: "Jabón de baño", categoria: "Higiene Personal", cantidad: 916 },
        { producto: "Jabón de lavar ropa", categoria: "Higiene Personal", cantidad: 36 },
        { producto: "Kit limpieza personal", categoria: "Higiene Personal", cantidad: 2 },
        { producto: "Limpiapisos", categoria: "Higiene Personal", cantidad: 14 },
        { producto: "Papel higiénico", categoria: "Higiene Personal", cantidad: 1917 },
        { producto: "Pasta dental", categoria: "Higiene Personal", cantidad: 505 },
        { producto: "Pañales para adulto", categoria: "Higiene Personal", cantidad: 420 },
        { producto: "Tampones", categoria: "Higiene Personal", cantidad: 3 },
        { producto: "Toallas para baño", categoria: "Higiene Personal", cantidad: 2 },
        { producto: "Toallas sanitarias", categoria: "Higiene Personal", cantidad: 5716 },
        { producto: "Vaselina", categoria: "Higiene Personal", cantidad: 3 },
        { producto: "Agujas hipodérmicas", categoria: "Medicina", cantidad: 36 },
        { producto: "Agujas pediátricas", categoria: "Medicina", cantidad: 454 },
        { producto: "Analgésicos Orales", categoria: "Medicina", cantidad: 4222 },
        { producto: "Antibióticos Inyectables", categoria: "Medicina", cantidad: 16 },
        { producto: "Antibióticos Penicilinas", categoria: "Medicina", cantidad: 322 },
        { producto: "Antibióticos Quinolonas", categoria: "Medicina", cantidad: 318 },
        { producto: "Anticonvulsivantes", categoria: "Medicina", cantidad: 57 },
        { producto: "Antidiabéticos e Insulina", categoria: "Medicina", cantidad: 301 },
        { producto: "Antieméticos", categoria: "Medicina", cantidad: 107 },
        { producto: "Antihipertensivos", categoria: "Medicina", cantidad: 5 },
        { producto: "Antihipertensivos IECA", categoria: "Medicina", cantidad: 921 },
        { producto: "Antihistamínicos", categoria: "Medicina", cantidad: 524 },
        { producto: "Antiinflamatorios Tópicos", categoria: "Medicina", cantidad: 3233 },
        { producto: "Antiparasitarios", categoria: "Medicina", cantidad: 56 },
        { producto: "Antisépticos", categoria: "Medicina", cantidad: 155 },
        { producto: "Antiácidos", categoria: "Medicina", cantidad: 143 },
        { producto: "Broncodilatadores", categoria: "Medicina", cantidad: 35 },
        { producto: "Catéter IV", categoria: "Medicina", cantidad: 844 },
        { producto: "Centro de cama", categoria: "Medicina", cantidad: 133 },
        { producto: "Corticoides Sistémicos", categoria: "Medicina", cantidad: 92 },
        { producto: "Corticoides Tópicos", categoria: "Medicina", cantidad: 11 },
        { producto: "Desinfectantes", categoria: "Medicina", cantidad: 516 },
        { producto: "Diagnóstico y Lab", categoria: "Medicina", cantidad: 432 },
        { producto: "Equipo pericraneal", categoria: "Medicina", cantidad: 1104 },
        { producto: "Guantes de látex", categoria: "Medicina", cantidad: 3830 },
        { producto: "Guantes de nitrilo", categoria: "Medicina", cantidad: 18829 },
        { producto: "Guantes de vinilo", categoria: "Medicina", cantidad: 215 },
        { producto: "Inmovilización", categoria: "Medicina", cantidad: 18 },
        { producto: "Instrumental Quirúrgico", categoria: "Medicina", cantidad: 562 },
        { producto: "Jeringas desechables", categoria: "Medicina", cantidad: 6528 },
        { producto: "Llave de 3 vías", categoria: "Medicina", cantidad: 32 },
        { producto: "Llave de 5 vías", categoria: "Medicina", cantidad: 3 },
        { producto: "Macrogoteros", categoria: "Medicina", cantidad: 385 },
        { producto: "Mascarillas N95", categoria: "Medicina", cantidad: 598 },
        { producto: "Mascarillas quirúrgicas", categoria: "Medicina", cantidad: 6921 },
        { producto: "Material de Curación", categoria: "Medicina", cantidad: 4616 },
        { producto: "Microgoteros", categoria: "Medicina", cantidad: 103 },
        { producto: "Obturador", categoria: "Medicina", cantidad: 218 },
        { producto: "Oncológicos", categoria: "Medicina", cantidad: 2 },
        { producto: "Oxigenoterapia", categoria: "Medicina", cantidad: 62 },
        { producto: "Pañales hospitalarios", categoria: "Medicina", cantidad: 123 },
        { producto: "Psiquiátricos", categoria: "Medicina", cantidad: 1 },
        { producto: "Rehidratación", categoria: "Medicina", cantidad: 152 },
        { producto: "Set de transfusión", categoria: "Medicina", cantidad: 44 },
        { producto: "Soluciones Intravenosas", categoria: "Medicina", cantidad: 880 },
        { producto: "Tapabocas tela", categoria: "Medicina", cantidad: 826 },
        { producto: "Tapaheparina", categoria: "Medicina", cantidad: 47 },
        { producto: "Vitaminas", categoria: "Medicina", cantidad: 749 },
        { producto: "Arnés de seguridad", categoria: "Materiales", cantidad: 1 },
        { producto: "Barreta", categoria: "Materiales", cantidad: 2 },
        { producto: "Botas seguridad", categoria: "Materiales", cantidad: 43 },
        { producto: "Casco seguridad", categoria: "Materiales", cantidad: 106 },
        { producto: "Cinta de seguridad", categoria: "Materiales", cantidad: 1 },
        { producto: "Cuerdas", categoria: "Materiales", cantidad: 8 },
        { producto: "Discos esmeril", categoria: "Materiales", cantidad: 145 },
        { producto: "Esmeril angular", categoria: "Materiales", cantidad: 3 },
        { producto: "Gafas protección", categoria: "Materiales", cantidad: 14 },
        { producto: "Guantes protección", categoria: "Materiales", cantidad: 1252 },
        { producto: "Lentes seguridad", categoria: "Materiales", cantidad: 101 },
        { producto: "Linternas", categoria: "Materiales", cantidad: 104 },
        { producto: "Martillos", categoria: "Materiales", cantidad: 30 },
        { producto: "Mascarilla anti-polvo", categoria: "Materiales", cantidad: 1006 },
        { producto: "Mazos", categoria: "Materiales", cantidad: 22 },
        { producto: "Palas", categoria: "Materiales", cantidad: 135 },
        { producto: "Palancas", categoria: "Materiales", cantidad: 6 },
        { producto: "Picos", categoria: "Materiales", cantidad: 28 },
        { producto: "Pilas", categoria: "Materiales", cantidad: 124 },
        { producto: "Sacos propileno", categoria: "Materiales", cantidad: 51 },
        { producto: "Sierras", categoria: "Materiales", cantidad: 7 },
        { producto: "Tobos", categoria: "Materiales", cantidad: 42 },
        { producto: "Comida gatos", categoria: "Mascotas", cantidad: 2 },
        { producto: "Gatarina", categoria: "Mascotas", cantidad: 17 },
        { producto: "Perrarina", categoria: "Mascotas", cantidad: 34 },
        { producto: "Almohada", categoria: "Otros", cantidad: 8 },
        { producto: "Cloro doméstico", categoria: "Otros", cantidad: 7 },
        { producto: "Cobija/frazada", categoria: "Otros", cantidad: 2 },
        { producto: "Colchoneta dormir", categoria: "Otros", cantidad: 74 },
        { producto: "Colchón individual", categoria: "Otros", cantidad: 6 },
        { producto: "Cubiertos", categoria: "Otros", cantidad: 105 },
        { producto: "Envases plásticos", categoria: "Otros", cantidad: 91 },
        { producto: "Guantes limpieza", categoria: "Otros", cantidad: 3 },
        { producto: "Kits sillas y mesas", categoria: "Otros", cantidad: 58 },
        { producto: "Lámpara recargable", categoria: "Otros", cantidad: 9 },
        { producto: "Papeleras", categoria: "Otros", cantidad: 4 },
        { producto: "Platos", categoria: "Otros", cantidad: 315 },
        { producto: "Termo", categoria: "Otros", cantidad: 2 },
        { producto: "Vasos", categoria: "Otros", cantidad: 1003 },
        { producto: "Velas", categoria: "Otros", cantidad: 146 }
    ];

    localStorage.setItem('inventarioAcopio', JSON.stringify(inventarioData));
    alert("¡Inventario cargado exitosamente! Recarga la página.");
}